version: '2'

services:
  elasticsearch:
    container_name: coordinator_es
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      LS_JAVA_OPTS: "-Xmx1024m -Xms1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
    volumes:
      - ./data/:/usr/share/elasticsearch/data:rw
      - ./log/:/usr/share/elasticsearch/log:rw
    restart: always
